name: CI
on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: 1.25
      - name: Test
        run: go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml --format pkgname

      - name: Test Summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2
        with:
          paths: "unit-tests.xml"
        if: always()

  release-please:
    name: Release
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  update-nix:
    name: Update Nix Flake
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update hashes
        id: update-hashes
        run: |
          # Get src hash
          sed -i 's#sha256 = ".*";#sha256 = "";#' flake.nix
          SRC_HASH=$(nix build 2>&1 | grep -oP 'got:\s+\Ksha256-[a-zA-Z0-9+\/]*' | head -1)
          sed -i "s#sha256 = \".*\";#sha256 = \"$SRC_HASH\";#" flake.nix

          # Get vendor hash
          sed -i 's#vendorHash = ".*";#vendorHash = "";#' flake.nix
          VENDOR_HASH=$(nix build 2>&1 | grep -oP 'got:\s+\Ksha256-[a-zA-Z0-9+\/]*' | head -1)
          sed -i "s#vendorHash = \".*\";#vendorHash = \"$VENDOR_HASH\";#" flake.nix
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        with:
          commit_message: "chore(nix): update flake.nix hashes"

  goreleaser:
    name: Publish
    needs: [release-please, update-nix]
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
