name: CI
on:
    push:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22
            - name: Test
              run: go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml --format pkgname

            - name: Test Summary
              uses: test-summary/action@v2
              with:
                  paths: "unit-tests.xml"
              if: always()
